export const save_MidClassRing = 'save_MidClassRing';
export const fiterName = 'fiterName';
export const fiterWeight = 'fiterWeight';
export const sortArr = 'sortArr';
export const clearAllFiter = 'clearAllFiter'
export const fiterShape = 'fiterShape';
export const fiterPrice ='fiterPrice';
export const pushClassRing = 'pushClassRing'
export const clearSort = 'clearSort'